### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by boxybird**
@Luc45 I was thinking the docs needed an update to mirror the new structure, but I didn't want to put the time in until you're done the major changes. Let me know when it's best to go though and edit them.

### CODE REVIEW

**Comment by Luc45** [comment]
I think a lot of MWW improvements will come with me and other people actually using it. I haven't got many opportunities to do so, because, on my work, we use another framework.

I happen to be coding a personal project in MWW right now, and even though I feel like I'm coding Laravel, not WordPress (which is a great feeling to have), I feel that the lack of Service Providers are being a pain point. I feel a lack of a place to register actions and register/group classes by context and functionality.

So, my next thing will probably be adding Service Providers to MWW.

I'm open to suggestions.

Thanks for the PR.

**Comment by Luc45** [comment]
@boxybird do you know what Service Providers are?

**Comment by boxybird** [comment]
@Luc45 Absolutely. I use Laravel and Lumen regularly.

**Comment by Luc45** [comment]
@boxybird I'll open an issue requesting Service Providers. Feel free to drop your feedback there, or open new issues requesting new features/ideas

**Pull request merged**
